"""Initial migration.

Revision ID: 015baa2685e4
Revises: 8ebab584e65a
Create Date: 2020-05-03 01:29:41.649409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015baa2685e4'
down_revision = '8ebab584e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search', sa.String(length=128), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search', sa.VARCHAR(length=128), nullable=True))
    op.drop_table('user_search')
    # ### end Alembic commands ###
